version: "3"
services:
  service_jekyll:
    image: local_jekyll
    container_name: local_jekyll_c
    environment:
      JEKYLL_UID: 1000
      JEKYLL_GID: 1000
    volumes:
      - ./_config.yml:/work/_config.yml
      - ./index.html:/work/index.html
      - ./_data/:/work/_data
      - ./_posts/:/work/_posts
      - ./_site/:/work/_site/
      - ./images/:/work/images
    command: jekyll serve -H 0.0.0.0 --watch --verbose --trace
    ports:
      - "4000:4000"